### ISSUE TITLE
Ideas for plots

### ISSUE THREAD

**Issue by cc7768** [NYUDataBootcamp/Materials#2]
Create a map of earth with a plot of all Nike factories -- Size of dot represents number of workers and color of dot represents percent workers female.

From enigma.io -- [dataset](https://app.enigma.io/table/com.nike.manufacturing-disclosures)

**Comment by cc7768** [comment]
gif of world which shades colors over time according to their net exports using UN comtrade data

Can get from enigma.io -- [dataset](https://app.enigma.io/table/org.un.comtrade.1)

**Comment by cc7768** [comment]
Make our own "[subway deserts](http://gothamist.com/2015/08/06/subway_desert_death_valley.php)" map. Could also do "closest station" voronoi map.

Can get from enigma.io -- [dataset](https://app.enigma.io/table/us.states.ny.mta.nycsubway.entrance-exit-locations?row=51&col=0&page=1)

Could also grab house prices and see whether on the voronoi diagram whether houses closest to the station were more expensive.

Also have data on how much each station gets used -- [dataset](https://app.enigma.io/table/us.states.ny.mta.fare-card-use)

**Comment by sglyon** [comment]
https://github.com/datanews/elevators

**Comment by sglyon** [comment]
The election will likely be a hot topic this fall. We should make an example/lab for that data.

**Comment by sglyon** [comment]
See other issues
