### ISSUE TITLE
Create a new exam

### ISSUE THREAD

**Issue by sglyon** [NYUDataBootcamp/Materials#20]
We posted the answers to the exam from spring in this repo...

![200](https://cloud.githubusercontent.com/assets/1001948/19442049/f2ac269a-9455-11e6-983b-f5f580b5932e.gif)

**Comment by cc7768** [comment]
For what its worth, I think we should write a new exam every semester. This gives them lots of practice exams which might mean students will do extra coding practice.

Good thing the undergrads have the exam first (assigns @spencerlyon2) ;) Just kidding -- Let's sit down and do this sometime this week.
