### ISSUE TITLE
Error on the practice exam

### ISSUE THREAD

**Issue by lillianpontiusgoldblatt** [NYUDataBootcamp/Materials#27]
Hi Guys!
I hope I'm doing this issue submission right. I'm getting an error accessing the practice exam. The answer key works.
Thanks!

![screenshot 2016-11-05 11 51 01](https://cloud.githubusercontent.com/assets/23280496/20031490/ab7b359c-a34e-11e6-94ee-899c363d9c91.png)

**Comment by sglyon** [comment]
This is a great place to post this!

Sometimes github fails to render render a preview of the notebook, even if the notebook is valid.

Have you tried clicking the raw button, downloading through file, and opening on your computer ?

**Comment by lillianpontiusgoldblatt** [comment]
Bingo! That worked. Thanks!
