### ISSUE TITLE
value_counts and groupby

### ISSUE THREAD

**Issue by cc7768** [NYUDataBootcamp/Materials#31]
We should really cover this method in the summarize notebook -- The groupby example that uses count could be done with this.

Using value_counts might make a good precursor to groupby? Would have to think more about how to draw connection, but definitely should cover value_counts.

**Comment by sglyon** [comment]
I definitely talked about it in at least one of these advanced pandas
lectures. Is it not in any notebook?

**Comment by cc7768** [comment]
It is. I must have missed it in the first pass as I was reviewing :frowning_man:
