### ISSUE TITLE
GDP typo in bootcamp_web_apis.ipynb

### ISSUE THREAD

**Issue by mwaugh0328** [NYUDataBootcamp/Materials#33]
There is an equation that says Y = C+I +H + NX

I think the H should be G!

Also this is a test for me...

**Comment by sglyon** [comment]
Excellent catch, thanks!

Typically you'd post this on the pull request over here: https://github.com/NYUDataBootcamp/Materials/pull/32

**Comment by cc7768** [comment]
:+1: Fixed it

**Comment by cc7768** [comment]
It won't be live until I've pushed my edits to the notebook though
